### ISSUE TITLE
Loading fails using PHP v5.2.10

### ISSUE THREAD

**Issue by shallin** [php-test-helpers/php-test-helpers#11]
When trying to load php on CentOS 5.5 with PHP version 5.2.10 I get the following error:

Failed loading /usr/lib/php/modules/test_helpers.so:  /usr/lib/php/modules/test_helpers.so: undefined symbol: zend_fcall_info_argn

During compile this is the only error I get:

/var/tmp/test_helpers/test_helpers.c:511: warning: initialization discards qualifiers from pointer target type

Any ideas on how to fix this?

**Comment by johannes** [comment]
This should be fixed in 78b9f94352ad2afbd09e8eb3d6b74cbc3b8888b0
