### ISSUE TITLE
Mock require / include statements

### ISSUE THREAD

**Issue by senseysensor** [php-test-helpers/php-test-helpers#19]
Is it possible to mock require / include statements?
It would be helpful sometimes in testing.

**Comment by wjaspers** [comment]
Perhaps these articles can help:
- http://blog.everymansoftware.com/2010/08/mocking-built-in-functions-in-php.html
- http://stackoverflow.com/questions/2326835/redefine-built-in-php-functions
- http://de.php.net/manual/en/function.override-function.php

**Comment by senseysensor** [comment]
Unfortunately require / include are not functions can be mocked, but are language constructs instead (http://www.php.net/manual/en/function.include.php)
But since this tool managed to mock in some sophisticated way exit / die construct, I hope it is principally possible to mock require / include as well.

Maybe someone more competent in php internal implementation could estimate is this task resolvable at all?

**Comment by sebastianbergmann** [comment]
This extension is [superseded](https://github.com/php-test-helpers/php-test-helpers/issues/29#issuecomment-44049111) by [uopz](https://github.com/krakjoe/uopz) and is no longer maintained.
