### ISSUE TITLE
Callback for the new operator should be invoked for non-existing classes

### ISSUE THREAD

**Issue by sebastianbergmann** [php-test-helpers/php-test-helpers#2]

**Comment by johannes** [comment]
See also #3

**Comment by antoineverger** [comment]
Any chance that this issue would be fixed ?!

**Comment by sebastianbergmann** [comment]
This extension is [superseded](https://github.com/php-test-helpers/php-test-helpers/issues/29#issuecomment-44049111) by [uopz](https://github.com/krakjoe/uopz) and is no longer maintained.
