### ISSUE TITLE
set_new_overload: return object instead of name of class to instantiate

### ISSUE THREAD

**Issue by ghost** [php-test-helpers/php-test-helpers#21]
When using the set_new_overload method, it would be great if one could return a (mocked) object that should be used as a new instance, instead of having to write a (mocked) class and returning its name. Furthermore, if returning the name of a mocked class, this will necessarily be different than the original class' name, with means it is not possible to test code that relies on the class name (my case exactly).

**Comment by sebastianbergmann** [comment]
This extension is [superseded](https://github.com/php-test-helpers/php-test-helpers/issues/29#issuecomment-44049111) by [uopz](https://github.com/krakjoe/uopz) and is no longer maintained.
