### ISSUE TITLE
Unable to use rename_function in Symfony2

### ISSUE THREAD

**Issue by alexdomsa** [php-test-helpers/php-test-helpers#24]
I was trying to use rename_function in unit testing some code in Symfony2. 

First I tried to rename an internal function and got an error. Wouldn't be nice to have this feature?

Than I tried with two simple methods in a test class but got another error:
rename_function(): rename_function(mock_method1, mock_method2) failed: mock_method1 does not exist!

The code looks like this:

``` php
<?php
namespace Functional\Test;

class FooTest
{
    public function testMethod()
    {
        $test = $this->mock_method1();

        rename_function('mock_method1', 'mock_method2');
        $test = $this->mock_method1();
    }

    public function mock_method1()
    {
        return false;
    }

    public function mock_method2()
    {
        return true;
    }
}
```

**Comment by whatthejeff** [comment]
Thanks for the bug report, @alexdomsa.

> First I tried to rename an internal function and got an error. Wouldn't be nice to have this feature?

Yea, we actually already have an issue open for this #8.

> Than I tried with two simple methods in a test class but got another error:

The syntax for renaming a method look like this:

``` php
rename_method('Functional\\Test\\FooTest', 'mock_method1', 'mock_method2');
```
