### ISSUE TITLE
Invoking a function of Mock class always returns NULL after calling set_new_overload

### ISSUE THREAD

**Issue by praveenrv** [php-test-helpers/php-test-helpers#27]
Hi,
In the below program, my intention is to unit test the validateIcao() function of 'Map_util' class. To handle the dependency injection, I have mocked the validateICAO() function of 'Airportinfo_util' class. Now when i m trying to run the test from 'mapUtilTest' class, the mocked function always returns NULL instead of returning 'valid' as string output which is expected. It would be helpful if you can let us know where we have gone wrong in configuring mock/writing test? 

<?php
//////// airportinfo_util.php /////////////
class Airportinfo_util 
{
    public function __construct($strServiceType="")
    {
    }
    public function validateICAO($icaoData)
    {
        if($icaoData == 'KSEA')
            return 'KSEA';
        else 
            return FALSE;
    }
}
?>
<?php
//////// map_util.php /////////////
//require_once 'airportinfo_util.php';
class Map_util
{
    public function __construct() { }

```
public function validateIcao($icao)
{
    $icao=trim(strtoupper($icao));
    $objIcaoValidator =  new Airportinfo_util("FPE");
    var_dump(get_class($objIcaoValidator));
    var_dump($objIcaoValidator->validateICAO($icao));
}
```

}
?>
<?php
//////// mapUtilTest.php /////////////
//require_once 'airportinfo_util.php';
//require_once 'map_util.php';

class mapUtilTest extends PHPUnit_Framework_TestCase 
{
    protected function setUp()
    {
        $mock = $this->getMockBuilder('Airportinfo_util')
                     ->setConstructorArgs(array('FPE'))
                     ->setMethods(array('validateICAO'))
                     ->setMockClassName('Mock_Airportinfo_util')
                     ->disableOriginalClone()
                     ->getMock();

```
    $map = array(
        array('KSEA', 'valid'),
        array('1234', 'invalid')
    );
    $mock->expects($this->any())
         ->method("validateICAO")
         ->will($this->returnValueMap($map)
    );
    set_new_overload(array($this, 'newCallback'));
}
protected function tearDown()
{
    unset_new_overload();
}
protected function newCallback($className)
{
    switch ($className) 
    {
        case 'Airportinfo_util':
                return 'Mock_Airportinfo_util';
        default:
                return $className;
    }
 }
public function testvalidateIcao()
{
    $map_util = new Map_util;
    $this->assertEquals('valid', $map_util->validateIcao('KSEA'));
}
```

}

?>

**Comment by sebastianbergmann** [comment]
This extension is [superseded](https://github.com/php-test-helpers/php-test-helpers/issues/29#issuecomment-44049111) by [uopz](https://github.com/krakjoe/uopz) and is no longer maintained.
