### ISSUE TITLE
Error Installing on Mac OSX

### ISSUE THREAD

**Issue by ciatog** [php-test-helpers/php-test-helpers#29]
I initially installed this extension without issue for PHP 5.4 on Mac OSX 10.9.2.

I got a new Macbook (same OSX version) but upgraded to PHP 5.5.12 but are receiving errors when trying to install the test helpers. The output is as follows:

downloading test_helpers-1.1.0.tgz ...
Starting to download test_helpers-1.1.0.tgz (10,370 bytes)
.....done: 10,370 bytes
4 source files, building
WARNING: php_bin /usr/local/Cellar/php55/5.5.12/bin/php appears to have a suffix 55/5.5.12/bin/php, but config variable php_suffix does not match
running: phpize
Configuring for:
PHP Api Version:         20121113
Zend Module Api No:      20121212
Zend Extension Api No:   220121212
building in /private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/pear-build-kwebsterHrdh5T/test_helpers-1.1.0
running: /private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/test_helpers/configure
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-apple-darwin13.1.0
checking host system type... x86_64-apple-darwin13.1.0
checking target system type... x86_64-apple-darwin13.1.0
checking for PHP prefix... /usr/local/Cellar/php55/5.5.12
checking for PHP includes... -I/usr/local/Cellar/php55/5.5.12/include/php -I/usr/local/Cellar/php55/5.5.12/include/php/main -I/usr/local/Cellar/php55/5.5.12/include/php/TSRM -I/usr/local/Cellar/php55/5.5.12/include/php/Zend -I/usr/local/Cellar/php55/5.5.12/include/php/ext -I/usr/local/Cellar/php55/5.5.12/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/Cellar/php55/5.5.12/lib/php/extensions/no-debug-non-zts-20121212
checking for PHP installed headers prefix... /usr/local/Cellar/php55/5.5.12/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... no
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking whether to enable test_helpers support... yes, shared
checking for ld used by cc... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking for /Library/Developer/CommandLineTools/usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 196608
checking command to parse /usr/bin/nm output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking if cc supports -fno-rtti -fno-exceptions... yes
checking for cc option to produce PIC... -fno-common
checking if cc PIC flag -fno-common works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin13.1.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
running: make
/bin/sh /private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/pear-build-kwebsterHrdh5T/test_helpers-1.1.0/libtool --mode=compile cc  -I. -I/private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/test_helpers -DPHP_ATOM_INC -I/private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/pear-build-kwebsterHrdh5T/test_helpers-1.1.0/include -I/private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/pear-build-kwebsterHrdh5T/test_helpers-1.1.0/main -I/private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/test_helpers -I/usr/local/Cellar/php55/5.5.12/include/php -I/usr/local/Cellar/php55/5.5.12/include/php/main -I/usr/local/Cellar/php55/5.5.12/include/php/TSRM -I/usr/local/Cellar/php55/5.5.12/include/php/Zend -I/usr/local/Cellar/php55/5.5.12/include/php/ext -I/usr/local/Cellar/php55/5.5.12/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/test_helpers/test_helpers.c -o test_helpers.lo
mkdir .libs
 cc -I. -I/private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/test_helpers -DPHP_ATOM_INC -I/private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/pear-build-kwebsterHrdh5T/test_helpers-1.1.0/include -I/private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/pear-build-kwebsterHrdh5T/test_helpers-1.1.0/main -I/private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/test_helpers -I/usr/local/Cellar/php55/5.5.12/include/php -I/usr/local/Cellar/php55/5.5.12/include/php/main -I/usr/local/Cellar/php55/5.5.12/include/php/TSRM -I/usr/local/Cellar/php55/5.5.12/include/php/Zend -I/usr/local/Cellar/php55/5.5.12/include/php/ext -I/usr/local/Cellar/php55/5.5.12/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/test_helpers/test_helpers.c  -fno-common -DPIC -o .libs/test_helpers.o
/private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/test_helpers/test_helpers.c:105:10: error: no member named 'Ts' in 'struct _zend_execute_data'
                return EX_T(node->u.var).var.ptr;
                       ^~~~~~~~~~~~~~~~~
/private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/test_helpers/test_helpers.c:95:54: note: expanded from macro 'EX_T'
# define EX_T(offset) (*(temp_variable *)((char *) EX(Ts) + offset))

```
                                              ~~~^~~
```

/private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/test_helpers/test_helpers.c:94:35: note: expanded from macro 'EX'
# define EX(element) execute_data->element

```
                              ^
```

/private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/test_helpers/test_helpers.c:105:23: error: no member named 'var' in 'union _znode::<anonymous at /usr/local/Cellar/php55/5.5.12/include/php/Zend/zend_compile.h:91:2>'
                return EX_T(node->u.var).var.ptr;
                            ~~~~~~~ ^
/private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/test_helpers/test_helpers.c:95:60: note: expanded from macro 'EX_T'
# define EX_T(offset) (*(temp_variable *)((char *) EX(Ts) + offset))

```
                                                       ^
```

/private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/test_helpers/test_helpers.c:107:23: error: no member named 'Ts' in 'struct _zend_execute_data'
                return (*freeval = &EX_T(node->u.var).tmp_var);
                                    ^~~~~~~~~~~~~~~~~
/private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/test_helpers/test_helpers.c:95:54: note: expanded from macro 'EX_T'
# define EX_T(offset) (*(temp_variable *)((char *) EX(Ts) + offset))

```
                                              ~~~^~~
```

/private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/test_helpers/test_helpers.c:94:35: note: expanded from macro 'EX'
# define EX(element) execute_data->element

```
                              ^
```

/private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/test_helpers/test_helpers.c:107:36: error: no member named 'var' in 'union _znode::<anonymous at /usr/local/Cellar/php55/5.5.12/include/php/Zend/zend_compile.h:91:2>'
                return (*freeval = &EX_T(node->u.var).tmp_var);
                                         ~~~~~~~ ^
/private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/test_helpers/test_helpers.c:95:60: note: expanded from macro 'EX_T'
# define EX_T(offset) (*(temp_variable *)((char *) EX(Ts) + offset))

```
                                                       ^
```

/private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/test_helpers/test_helpers.c:110:32: error: no member named 'CVs' in 'struct _zend_execute_data'
                zval _**ret = &execute_data->CVs[node->u.var];
                               ~~~~~~~~~~~~  ^
/private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/test_helpers/test_helpers.c:110:44: error: no member named 'var' in 'union _znode::<anonymous at /usr/local/Cellar/php55/5.5.12/include/php/Zend/zend_compile.h:91:2>'
                zval *_*ret = &execute_data->CVs[node->u.var];
                                                 ~~~~~~~ ^
/private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/test_helpers/test_helpers.c:112:69: error: no member named 'var' in 'union _znode::<anonymous at /usr/local/Cellar/php55/5.5.12/include/php/Zend/zend_compile.h:91:2>'
                                zend_compiled_variable *cv = &EG(active_op_array)->vars[node->u.var];
                                                                                        ~~~~~~~ ^
/private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/test_helpers/test_helpers.c:168:11: error: no member named 'Ts' in 'struct _zend_execute_data'
        old_ce = EX_T(opline->op1.u.var).class_entry;
                 ^~~~~~~~~~~~~~~~~~~~~~~
/private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/test_helpers/test_helpers.c:95:54: note: expanded from macro 'EX_T'
# define EX_T(offset) (*(temp_variable *)((char *) EX(Ts) + offset))

```
                                              ~~~^~~
```

/private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/test_helpers/test_helpers.c:94:35: note: expanded from macro 'EX'
# define EX(element) execute_data->element

```
                              ^
```

/private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/test_helpers/test_helpers.c:168:28: error: no member named 'u' in 'union _znode_op'
        old_ce = EX_T(opline->op1.u.var).class_entry;
                      ~~~~~~~~~~~ ^
/private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/test_helpers/test_helpers.c:95:60: note: expanded from macro 'EX_T'
# define EX_T(offset) (*(temp_variable *)((char *) EX(Ts) + offset))

```
                                                       ^
```

/private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/test_helpers/test_helpers.c:192:2: error: no member named 'Ts' in 'struct _zend_execute_data'
        EX_T(opline->op1.u.var).class_entry = *new_ce;
        ^~~~~~~~~~~~~~~~~~~~~~~
/private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/test_helpers/test_helpers.c:95:54: note: expanded from macro 'EX_T'
# define EX_T(offset) (*(temp_variable *)((char *) EX(Ts) + offset))

```
                                              ~~~^~~
```

/private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/test_helpers/test_helpers.c:94:35: note: expanded from macro 'EX'
# define EX(element) execute_data->element

```
                              ^
```

/private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/test_helpers/test_helpers.c:192:19: error: no member named 'u' in 'union _znode_op'
        EX_T(opline->op1.u.var).class_entry = *new_ce;
             ~~~~~~~~~~~ ^
/private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/test_helpers/test_helpers.c:95:60: note: expanded from macro 'EX_T'
# define EX_T(offset) (*(temp_variable *)((char *) EX(Ts) + offset))

```
                                                       ^
```

/private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/test_helpers/test_helpers.c:215:25: warning: incompatible pointer types passing 'znode_op _' (aka 'union _znode_op *') to parameter of type 'znode *' (aka 'struct _znode *') [-Wincompatible-pointer-types]
        msg = pth_get_zval_ptr(&EX(opline)->op1, &freeop, execute_data TSRMLS_CC);
                               ^~~~~~~~~~~~~~~~
/private/var/folders/tx/vmtc_mvs3qvfvbgj3llt_7300000gn/T/pear/temp/test_helpers/test_helpers.c:97:38: note: passing argument to parameter 'node' here
static zval *pth_get_zval_ptr(znode *node, zval *_freeval, zend_execute_data _execute_data TSRMLS_DC) /_ {{{ _/
                                     ^
1 warning and 11 errors generated.
make: *_\* [test_helpers.lo] Error 1
ERROR: `make' failed

Let me know if you need further information.

Thanks for your help

**Comment by whatthejeff** [comment]
Could you try the instructions listed [here](https://github.com/php-test-helpers/php-test-helpers/issues/23#issuecomment-29418653)?

**Comment by ciatog** [comment]
Perfect! That did the job.

A similar issue was happening for a colleague of mine on the latest version of Ubuntu and it resolved that as well. 

Thanks!

**Comment by whatthejeff** [comment]
No problem. 

@johannes, @sebastianbergmann: Any plans on tagging a release for these fixes?

**Comment by sebastianbergmann** [comment]
Not really as this extension is superseded by https://github.com/krakjoe/uopz

**Comment by whatthejeff** [comment]
@sebastianbergmann should we add a note to the readme about that?

**Comment by sebastianbergmann** [comment]
Sure, why not.
