### ISSUE TITLE
Investigate whether FETCH_CLASS can be overloaded

### ISSUE THREAD

**Issue by sebastianbergmann** [php-test-helpers/php-test-helpers#3]
Investigate whether the `FETCH_CLASS` opcode can be overloaded instead of `NEW`.

This is related to #2 and would also allow to intercept and redirect static method calls.

**Comment by mathieuk** [comment]
Did some digging. To cover these use cases:

<pre>
MyClass::doStuff();
MyClass::MY_CONST;
MyClass::$my_static;
$x::MY_CONST;

new MyClass();
$y = "MyClass"; new $y(); 
</pre>


.. you'd have to overload ZEND_INIT_STATIC_METHOD_CALL, FETCH_CONSTANT and ZEND_FETCH_CLASS. There you could have a callback (much in the same way set_new_overload() does now) to determine the preferred classname just like set_new_overload().

**Comment by sebastianbergmann** [comment]
This extension is [superseded](https://github.com/php-test-helpers/php-test-helpers/issues/29#issuecomment-44049111) by [uopz](https://github.com/krakjoe/uopz) and is no longer maintained.
