### ISSUE TITLE
how to make it work which php version is 5.2 and exist with params

### ISSUE THREAD

**Issue by jiansongjay** [php-test-helpers/php-test-helpers#31]
my php version is 5.2. It cannot write like set_exit_overload(function($param){}). It dose not have anonymous function. So how can I make 'exit(0)' work.

**Comment by sebastianbergmann** [comment]
This extension is no longer maintained. Please use https://github.com/krakjoe/uopz instead.

**Comment by jiansongjay** [comment]
but my version is 5.2. uopz need 5.4 or higher. I just want to overload exit($param). How can I use set_exit_overload to make it work without anonymous function. Thank you.

**Comment by sebastianbergmann** [comment]
Just don't use an anonymous function then. Use a regular function and pass its name as a string to `set_exit_overload()`.

**Comment by jiansongjay** [comment]
![image](https://cloud.githubusercontent.com/assets/2103028/3790623/82548efc-1b10-11e4-8f9c-036657536139.png)

my code show like this. And some error happened. It said that 'test_helpers.so: undefined symbol: zend_fcall_info_argn'

**Comment by johannes** [comment]
This indeed is a bug, on the other hand PHP5.2 is out of support for more than 3 years and this extension found a replacement. I reopen the bu anyways in case some developer has the time and motivation to fix this. As a work-around you should be able to use an older version of this extension. But you seriously should update to PHP 5.5.

**Comment by whatthejeff** [comment]
@johannes Seems this should be fixed by 78b9f94. I think it just never made it into an actual release.

**Comment by whatthejeff** [comment]
@jiansongjay Would you mind trying the instructions [here](https://github.com/php-test-helpers/php-test-helpers/issues/23#issuecomment-29418653) to see if they fix the issue?

**Comment by jiansongjay** [comment]
@whatthejeff  git clone git@github.com:php-test-helpers/php-test-helpers.git  . It cannot git clone. 
![image](https://cloud.githubusercontent.com/assets/2103028/3792597/f4844b22-1b7c-11e4-9373-8d326491ecb5.png)

**Comment by jiansongjay** [comment]
My version is git clone from  'git clone https://github.com/php-test-helpers/php-test-helpers.git'.

**Comment by whatthejeff** [comment]
@jiansongjay That's fine. Were you able to follow the rest of the instructions?

**Comment by jiansongjay** [comment]
It dosen't work after I follow your instructions. The error is also ‘undefined symbol: UNEXPECTED’ when I overload exit（0）. 
my test_helpers is v1.0.1-dev, php-version is 5.2.17,

**Comment by whatthejeff** [comment]
@jiansongjay That should be an easy fix. Give me a couple hours to get around to it.

**Comment by whatthejeff** [comment]
@jiansongjay Can you pull in the latest changes and try to build the extension again? All tests are passing on 5.2 for me.

**Comment by whatthejeff** [comment]
@jiansongjay Your `_exit()` function needs to return false if you don't want to exit :)

**Comment by jiansongjay** [comment]
Thank you very much. It works.

**Comment by whatthejeff** [comment]
Thanks for your patience, @jiansongjay :)

**Comment by whatthejeff** [comment]
@jiansongjay PS: You should really upgrade PHP if possible. PHP 5.2 hasn't received any security updates since January 2011.
