### ISSUE TITLE
pear is shutdown on 31 Dec 2014

### ISSUE THREAD

**Issue by nghenglim** [php-test-helpers/php-test-helpers#32]
According to https://github.com/sebastianbergmann/phpunit/wiki/End-of-Life-for-PEAR-Installation-Method

```
The process of retiring pear.phpunit.de was tracked in ticket #1229. The final step was the shutdown of pear.phpunit.de on December 31, 2014.
```

As a result, the project readme installation guide is not working anymore

**Comment by sebastianbergmann** [comment]
This extension is [superseded](https://github.com/php-test-helpers/php-test-helpers/issues/29#issuecomment-44049111) by [uopz](https://github.com/krakjoe/uopz) and is no longer maintained.
