### ISSUE TITLE
Pear Install - Windows (dll?)

### ISSUE THREAD

**Issue by carlosantana** [php-test-helpers/php-test-helpers#6]
pecl install phpunit/test_helpers
downloading test_helpers-1.0.0.tgz ...
Starting to download test_helpers-1.0.0.tgz (6,980 bytes)
.....done: 6,980 bytes
4 source files, building
WARNING: php_bin D:\PHP5\php.exe appears to have a suffix .exe, but config variable php_suffix does not match
ERROR: The DSP test_helpers.dsp does not exist.

**Comment by carlosantana** [comment]
Any hope for dll?

**Comment by jmabey** [comment]
yes, will there be a dll?

**Comment by johannes** [comment]
You can try these temporary builds of current git revisions (0c94ba29d59835d60e5f467ddd134aa50363426a): http://www.clantemplates.com/kalle/downloads/

**Comment by vlatek** [comment]
Both php_test_helpers-VC9-x86-TS.dll from http://www.clantemplates.com/kalle/downloads/
and
php_test_helpers.dll (php_test_helpers-5.3-snap-20101203-vc6-x86.zip) from http://downloads.php.net/pierre/ 
give me error
C:\Program Files\PHP5\ext\php_test_helpers.dll doesn't appear to be a valid Zend extension
with PHP 5.3.5, Xdebug 2.1.1 and zend_extension=... after zend_extension=...php_xdebug in php.ini.

Loading as PHP (not Zend) extension without Xdebug works.

**Comment by MartyIX** [comment]
I tried to, at least, get rid of the warning. The command:

   pecl config-set php_suffix .exe 

does not seem to work.

**Comment by ArtemGoutsoul** [comment]
I have the same issue:
C:>pecl install phpunit/test_helpers
downloading test_helpers-1.1.0.tgz ...
Starting to download test_helpers-1.1.0.tgz (10,370 bytes)
.....done: 10,370 bytes
4 source files, building
WARNING: php_bin C:\wamp\bin\php\php5.3.8\php.exe appears to have a suffix \php5.3.8\php.exe, but config variable php_suffix does not match
ERROR: The DSP test_helpers.dsp does not exist.

Using "pecl config-set php_suffix .exe" did not change anything.

**Comment by sebastianbergmann** [comment]
So it's a Windows issue and not a general issue. Sorry but I won't be able to help with creating DSP/DSW files and add those to the distribution. The distribution does have a `config.w32` file, though. No idea why that is not used.

**Comment by Spudley** [comment]
I can echo the comments of others that the installer does not work on Windows. I guess that's obvious if there isn't a DLL in the repository.

As per tuk66's comment, the compiled DLL on http://downloads.php.net/pierre/ works, provided you use extension=... rather than zend_extension=... in php.ini, and provided you also disable xDebug.

So it works, but it's not an ideal solution. Disappointing, as I'd sold it to the team as a solution to our problems with writing unit tests for the legacy code. But as things stand, it probably raises more issues than it solves.

**Comment by BrentNewland** [comment]
This isn't a Windows issue, it's an issue with the PEAR scripts.

This bug is the root cause of the problem: http://pear.php.net/bugs/bug.php?id=17016

It seems the temporary folder that the source code is unpacked to is deleted before the install process starts, thus the DSP file is gone.

**Comment by dresh** [comment]
why is it closed? 
the issue still persists

**Comment by dresh** [comment]
having the same problem while trying to 
pecl install apc

**Comment by sebastianbergmann** [comment]
This is closed because the whole project is closed.

**Comment by dresh** [comment]
oh ok..

**Comment by mbpakalin** [comment]
pecl config-set php_suffix \php.exe 
solved my problem.

**Comment by sbala69gmail** [comment]
I am also same problem to install oauth file..

```
pecl install oauth                                 
downloading oauth-2.0.2.tgz ...                      
Starting to download oauth-2.0.2.tgz (49,115 bytes)  
.............done: 49,115 bytes                      
6 source files, building                             
ERROR: The DSP oauth.dsp does not exist.            
```

Help any one.
