### ISSUE TITLE
PECL Install failing based on zend_fcall_info not having a member named 'object_ptr'

### ISSUE THREAD

**Issue by ematta** [php-test-helpers/php-test-helpers#7]
Cant do a PECL install for this tool. Make fails. 
# 
# PECL Install Output

ematta@ematta-desktop:~$ sudo pecl install -f phpunit/test_helpers
downloading test_helpers-1.0.0.tgz ...
Starting to download test_helpers-1.0.0.tgz (6,980 bytes)
.....done: 6,980 bytes
4 source files, building
running: phpize
Configuring for:
PHP Api Version:         20041225
Zend Module Api No:      20060613
Zend Extension Api No:   220060519
building in /var/tmp/pear-build-root/test_helpers-1.0.0
running: /tmp/pear/temp/test_helpers/configure
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables...
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib
checking for PHP extension directory... /usr/lib/php5/20060613
checking for PHP installed headers prefix... /usr/include/php5
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... gawk
checking whether to enable test_helpers support... yes, shared
checking for a sed that does not truncate output... (cached) /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for ar... ar
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC -DPIC
checking if cc PIC flag -fPIC -DPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking if cc supports -c -o file.o... (cached) yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
configure: creating ./config.status
config.status: creating config.h
config.status: executing libtool commands
running: make
/bin/bash /var/tmp/pear-build-root/test_helpers-1.0.0/libtool --mode=compile cc  -I. -I/tmp/pear/temp/test_helpers -DPHP_ATOM_INC -I/var/tmp/pear-build-root/test_helpers-1.0.0/include -I/var/tmp/pear-build-root/test_helpers-1.0.0/main -I/tmp/pear/temp/test_helpers -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/test_helpers/test_helpers.c -o test_helpers.lo
libtool: compile:  cc -I. -I/tmp/pear/temp/test_helpers -DPHP_ATOM_INC -I/var/tmp/pear-build-root/test_helpers-1.0.0/include -I/var/tmp/pear-build-root/test_helpers-1.0.0/main -I/tmp/pear/temp/test_helpers -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/test_helpers/test_helpers.c  -fPIC -DPIC -o .libs/test_helpers.o
/tmp/pear/temp/test_helpers/test_helpers.c: In function ‘test_helpers_free_new_handler’:
/tmp/pear/temp/test_helpers/test_helpers.c:68: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
/tmp/pear/temp/test_helpers/test_helpers.c:69: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
/tmp/pear/temp/test_helpers/test_helpers.c:70: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
/tmp/pear/temp/test_helpers/test_helpers.c: In function ‘php_test_helpers_init_globals’:
/tmp/pear/temp/test_helpers/test_helpers.c:120: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
/tmp/pear/temp/test_helpers/test_helpers.c: In function ‘zif_set_new_overload’:
/tmp/pear/temp/test_helpers/test_helpers.c:183: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
/tmp/pear/temp/test_helpers/test_helpers.c:184: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
/tmp/pear/temp/test_helpers/test_helpers.c: At top level:
/tmp/pear/temp/test_helpers/test_helpers.c:218: warning: initialization discards qualifiers from pointer target type
make: **\* [test_helpers.lo] Error 1
ERROR: `make' failed
# 
# PECL Config
# Configuration (channel pecl.php.net):

Auto-discover new Channels     auto_discover    <not set>
Default Channel                default_channel  pecl.php.net
HTTP Proxy Server Address      http_proxy       <not set>
PEAR server [DEPRECATED]       master_server    pear.php.net
Default Channel Mirror         preferred_mirror pecl.php.net
Remote Configuration File      remote_config    <not set>
PEAR executables directory     bin_dir          /usr/bin
PEAR documentation directory   doc_dir          /usr/share/php/doc
PHP extension directory        ext_dir          /usr/lib/php5/20060613+lfs
PEAR directory                 php_dir          /usr/share/php
PEAR Installer cache directory cache_dir        /tmp/pear/cache
PEAR configuration file        cfg_dir          /usr/share/php/cfg
directory
PEAR data directory            data_dir         /usr/share/php/data
PEAR Installer download        download_dir     /build/buildd/php5-5.2.10.dfsg.1/pear-build-download
directory
PHP CLI/CGI binary             php_bin          /usr/bin/php
php.ini location               php_ini          <not set>
--program-prefix passed to     php_prefix       <not set>
PHP's ./configure
--program-suffix passed to     php_suffix       <not set>
PHP's ./configure
PEAR Installer temp directory  temp_dir         /tmp/pear/temp
PEAR test directory            test_dir         /usr/share/php/test
PEAR www files directory       www_dir          /usr/share/php/htdocs
Cache TimeToLive               cache_ttl        3600
Preferred Package State        preferred_state  stable
Unix file mask                 umask            22
Debug Log Level                verbose          1
PEAR password (for             password         <not set>
maintainers)
Signature Handling Program     sig_bin          /usr/bin/gpg
Signature Key Directory        sig_keydir       /etc/pear/pearkeys
Signature Key Id               sig_keyid        <not set>
Package Signature Type         sig_type         gpg
PEAR username (for             username         <not set>
maintainers)
User Configuration File        Filename         /home/ematta/.pearrc
System Configuration File      Filename         /etc/pear/pear.conf

**Comment by johannes** [comment]
The code was developed and tested with PHP 5.3 in mind, if I find the time I'll try supporting 5.2 but I won't promise anything.

**Comment by ematta** [comment]
Thanks for the support! :D

**Comment by johannes** [comment]
Fixed in f5997f5ae4ff1f878fd9396a801d809b4d138333 mind that a few test cases fail which is ok as they either verify closure support, which doesn't work on 5.2  or some error messages changed. I'd like to keep the error messages unchanged, the closure ones might be skipped.

**Comment by johannes** [comment]
In 922c6ebfd9ab48a07463b0f5ebbb4346779a98cf two tests are set to be skipped.
tests/set_new_overload_error_undefined_callback.phpt and tests/set_new_overload_private_method.phpt will still fail.

**Comment by ematta** [comment]
Thank you very much for all your hard work on this. When will it be uploaded to the pecl repository so I can tell my co-workers to get it?
