### ISSUE TITLE
Rename internal functions

### ISSUE THREAD

**Issue by Weltraumschaf** [php-test-helpers/php-test-helpers#8]
Would be nice to rename internal php functions.

**Comment by ghost** [comment]
:+1: 

Just ran into this issue myself. I was hoping to use it in place of runkit.

**Comment by ghost** [comment]
Would come in hand for me as well

**Comment by georgiana-gligor** [comment]
+1
I found the [unit test](https://github.com/sebastianbergmann/php-test-helpers/blob/master/tests/rename_internal_function.phpt) but the functionality is still not there. 
An implementation of this would be so helpful!

Adding the error message here so other Googlers can find it; I was trying to rename the `disk_free_space` method.

`rename_function(): "disk_free_space" is an internal function`

**Comment by senseysensor** [comment]
+1

**Comment by georgiana-gligor** [comment]
+1
What needs to happen to implement this? Need any help with this?

**Comment by ghost** [comment]
Maybe some code should be borrowed from [Dmitry's fork](https://github.com/zenovich/runkit) of the runkit extension?

**Comment by sebastianbergmann** [comment]
This extension is [superseded](https://github.com/php-test-helpers/php-test-helpers/issues/29#issuecomment-44049111) by [uopz](https://github.com/krakjoe/uopz) and is no longer maintained.
